apiVersion: v2
name: anvil
description: k8s-native Minecraft server panel
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://gitlab.cherkaoui.ch/HadiCherkaoui/anvil
maintainers:
  - name: HadiCherkaoui
